// STOCKS
export const SET_POPULAR_STOCKS_LOADING = "SET_POPULAR_STOCKS_LOADING";
export const FETCH_MOST_POPULAR_STOCK_SUCCESS = "FETCH_MOST_POPULAR_STOCK_SUCCESS";
export const FETCH_STOCK_IN_INTERVAL_SUCCESS = "FETCH_STOCK_IN_INTERVAL_SUCCESS";

export const SET_INTERVAL_STOCK_LOADING = "SET_INTERVAL_STOCK_LOADING";
