// STOCKS
export const SET_POPULAR_STOCKS_LOADING = "SET_POPULAR_STOCKS_LOADING";
export const FETCH_MOST_POPULAR_STOCK_SUCCESS = "FETCH_MOST_POPULAR_STOCK_SUCCESS";
export const FETCH_STOCK_IN_INTERVAL_SUCCESS = "FETCH_STOCK_IN_INTERVAL_SUCCESS";
export const SET_INTERVAL_STOCK_LOADING = "SET_INTERVAL_STOCK_LOADING";
export const FETCH_LATEST_STOCK_VALUES_SUCCESS = "FETCH_LATEST_STOCK_VALUES_SUCCESS";
export const SEARCH_STOCKS_SUCCESS = "SEARCH_STOCKS_SUCCESS";
export const SET_SEARCH_STOCKS_LOADING = "SET_SEARCH_STOCKS_LOADING";
export const FETCH_STOCKS_EXCHANGES_SUCCESS = "FETCH_STOCKS_EXCHANGES_SUCCESS";
export const FETCH_DETAILS_DATA = "FETCH_DETAILS_DATA_SUCCESS";
export const FETCH_STOCKS_DETAILS = "FETCH_STOCKS_DETAILS_SUCCESS";
export const EPS_COMPANY_PER_YEAR = "EPS_COMPANY_PER_YEAR";
export const FETCH_REPORTS_DATA = "FETCH_REPORTS_DATA";

export const FETCH_COMPANY_RECOMMENDATION_TRENDS_SUCCESS = "FETCH_COMPANY_RECOMMENDATION_TRENDS_SUCCESS";
export const FETCH_COMPANY_RECOMMENDATION_TRENDS_LOADING = "FETCH_COMPANY_RECOMMENDATION_TRENDS_LOADING";

export const FETCH_COMPANY_PRODUCTS_WIKI_LINKS_SUCCESS = "FETCH_COMPANY_PRODUCTS_WIKI_LINKS_SUCCESS";
export const FETCH_COMPANY_PRODUCTS_WIKI_LINKS_LOADING = "FETCH_COMPANY_PRODUCTS_WIKI_LINKS_LOADING";
export const FETCH_COMPANY_SERVICES_WIKI_LINKS_SUCCESS = "FETCH_COMPANY_SERVICES_WIKI_LINKS_SUCCESS";
export const FETCH_COMPANY_SERVICES_WIKI_LINKS_LOADING = "FETCH_COMPANY_SERVICES_WIKI_LINKS_LOADING";
export const FETCH_COMPANY_DEVELOPMENTS_WIKI_LINKS_SUCCESS = "FETCH_COMPANY_DEVELOPMENTS_WIKI_LINKS_SUCCESS";
export const FETCH_COMPANY_DEVELOPMENTS_WIKI_LINKS_LOADING = "FETCH_COMPANY_DEVELOPMENTS_WIKI_LINKS_LOADING";
export const FETCH_COMPANY_DESIGNS_WIKI_LINKS_SUCCESS = "FETCH_COMPANY_DESIGNS_WIKI_LINKS_SUCCESS";
export const FETCH_COMPANY_DESIGNS_WIKI_LINKS_LOADING = "FETCH_COMPANY_DESIGNS_WIKI_LINKS_LOADING";

// CRYPTOCURRENCIES
export const FETCH_COINS_MARKET_DATA_SUCCESS = "FETCH_COINS_MARKET_DATA_SUCCESS";
export const SET_COINS_MARKET_DATA_LOADING = "SET_COINS_MARKET_DATA_LOADING";
export const FETCH_EXCHANGES_SUCCESS = "FETCH_EXCHANGES_SUCCESS";
export const SET_EXCHANGES_LOADING = "SET_EXCHANGES_LOADING";

export const FETCH_COIN_DETAILS_SUCCESS = "FETCH_COIN_DETAILS_SUCCESS";
export const FETCH_COIN_OHCL_DATA_SUCCESS = "FETCH_COIN_OHCL_DATA_SUCCESS"
export const FETCH_COIN_MARKET_CHART_DATA_SUCCESS = "FETCH_COIN_MARKET_CHART_DATA_SUCCESS"

export const FETCH_COIN_ABSTRACT_SUCCESS = "FETCH_COIN_ABSTRACT_SUCCESS";

// NEWS
export const FETCH_STOCKS_MARKET_NEWS_SUCCESS = "FETCH_STOCKS_MARKET_NEWS_SUCCESS";
export const FETCH_CRYPTOCURRENCY_NEWS_SUCCESS = "FETCH_CRYPTOCURRENCY_NEWS_SUCCESS";
export const SET_STOCKS_NEWS_LOADING = "SET_STOCKS_NEWS_LOADING";
export const SET_CRYPTO_NEWS_LOADING = "SET_CRYPTO_NEWS_LOADING";
