// STOCKS
export const SET_POPULAR_STOCKS_LOADING = "SET_POPULAR_STOCKS_LOADING";
export const FETCH_MOST_POPULAR_STOCK_SUCCESS = "FETCH_MOST_POPULAR_STOCK_SUCCESS";
export const FETCH_STOCK_IN_INTERVAL_SUCCESS = "FETCH_STOCK_IN_INTERVAL_SUCCESS";
export const SET_INTERVAL_STOCK_LOADING = "SET_INTERVAL_STOCK_LOADING";
export const FETCH_LATEST_STOCK_VALUES_SUCCESS = "FETCH_LATEST_STOCK_VALUES_SUCCESS";
export const SEARCH_STOCKS_SUCCESS = "SEARCH_STOCKS_SUCCESS";
export const SET_SEARCH_STOCKS_LOADING = "SET_SEARCH_STOCKS_LOADING";
export const FETCH_STOCKS_EXCHANGES_SUCCESS = "FETCH_STOCKS_EXCHANGES_SUCCESS";

// CRYPTOCURRENCIES
export const FETCH_COINS_MARKET_DATA_SUCCESS = "FETCH_COINS_MARKET_DATA_SUCCESS";
export const SET_COINS_MARKET_DATA_LOADING = "SET_COINS_MARKET_DATA_LOADING";
export const FETCH_EXCHANGES_SUCCESS = "FETCH_EXCHANGES_SUCCESS";
export const SET_EXCHANGES_LOADING = "SET_EXCHANGES_LOADING";

export const FETCH_COIN_DETAILS_SUCCESS = "FETCH_COIN_DETAILS_SUCCESS";

// NEWS
export const FETCH_STOCKS_MARKET_NEWS_SUCCESS = "FETCH_STOCKS_MARKET_NEWS_SUCCESS";
export const SET_STOCKS_NEWS_LOADING = "SET_STOCKS_NEWS_LOADING";
